//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCHOOL_MANAGEMENT.CAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AULA
    {
        public int Aula_codigo { get; set; }
        public string Aula_numerocurso { get; set; }
        public short Estadodeaula_codigo { get; set; }
        public byte Aula_capacidad { get; set; }
        public System.DateTime Aula_FechaCreacion { get; set; }
        public System.DateTime Aula_FechaModificacion { get; set; }
        public int Usuario_codigo { get; set; }
    }
}
