//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCHOOL_MANAGEMENT.CAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTE_SECCION
    {
        public int EstudianteSeccion_codigo { get; set; }
        public int Estudiante_codigo { get; set; }
        public int Seccion_codigo { get; set; }
    }
}
