//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCHOOL_MANAGEMENT.CAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTE
    {
        public int Estudiante_codigo { get; set; }
        public string Estudiante_nombre { get; set; }
        public string Estudiante_apellido { get; set; }
        public System.DateTime Estudiante_fechanac { get; set; }
        public string Estudiante_direccion { get; set; }
        public string Estudiante_email { get; set; }
        public string Estudiante_telefono { get; set; }
        public string Estudiante_celular { get; set; }
        public string Estudiante_estadocivil { get; set; }
        public string Estudiante_sexo { get; set; }
        public byte[] Estudiante_foto { get; set; }
        public int Seccion_codigo { get; set; }
        public System.DateTime Estudiante_FechaCreacion { get; set; }
        public System.DateTime Estudiante_FechaModificacion { get; set; }
        public int Usuario_codigo { get; set; }
    }
}
