//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCHOOL_MANAGEMENT.CAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESOR
    {
        public int Profesor_codigo { get; set; }
        public string Profesor_nombre { get; set; }
        public string Profesor_apellido { get; set; }
        public System.DateTime Profesor_fechanac { get; set; }
        public string Profesor_estadocivil { get; set; }
        public string Profesor_nacionalidad { get; set; }
        public string Profesor_cedula { get; set; }
        public string Profesor_email { get; set; }
        public string Profesor_sexo { get; set; }
        public string Profesor_direccion { get; set; }
        public string Profesor_telefono1 { get; set; }
        public string Profesor_telefono2 { get; set; }
        public int Seccion_codigo { get; set; }
        public byte[] Profesor_foto { get; set; }
        public System.DateTime Profesor_FechaCreacion { get; set; }
        public System.DateTime Profesor_FechaModificacion { get; set; }
        public int Usuario_codigo { get; set; }
    }
}
