//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCHOOL_MANAGEMENT.CAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECCION
    {
        public int Seccion_codigo { get; set; }
        public string Seccion_horario { get; set; }
        public int Capacitacion_codigo { get; set; }
        public int Profesor_codigo { get; set; }
        public string Seccion_cupo { get; set; }
        public int Aula_codigo { get; set; }
        public System.DateTime Seccion_fechai { get; set; }
        public System.DateTime Seccion_fechaf { get; set; }
        public System.DateTime Seccion_FechaCreacion { get; set; }
        public System.DateTime Seccion_FechaModificacion { get; set; }
        public int Usuario_codigo { get; set; }
    }
}
